/**
 * Verifies Razorpay payment signature using native Deno Web Crypto API.
 * Ref: https://razorpay.com/docs/payments/payment-gateway/web-integration/standard/integration-steps/#step-5-verify-signature
 * 
 * Signature is generated by hashing orderId + "|" + paymentId using HMAC-SHA256 with keySecret.
 */
export async function verifyRazorpaySignature(
  orderId: string,
  paymentId: string,
  signature: string,
  secret: string
): Promise<boolean> {
  const textEncoder = new TextEncoder();
  const data = textEncoder.encode(`${orderId}|${paymentId}`);
  const secretKey = textEncoder.encode(secret);

  const cryptoKey = await crypto.subtle.importKey(
    'raw',
    secretKey,
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );

  const signatureBuffer = await crypto.subtle.sign(
    'HMAC',
    cryptoKey,
    data
  );

  // Convert signatureBuffer to hex string
  const hashArray = Array.from(new Uint8Array(signatureBuffer));
  const generatedSignature = hashArray
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');

  return generatedSignature === signature;
}
